version: "3.9"

networks:
  ideiasia:
    external: true

services:
  gl-app:
    image: antonioferrao/hotel-campaign-cards:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
      VITE_SUPABASE_PROJECT_ID: ${VITE_SUPABASE_PROJECT_ID}
      VITE_APP_TITLE: Hotel Campaign Cards
    networks:
      - ideiasia
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gl.rule=Host(`gl.oceaniaparkhotel.com.br`)"
      - "traefik.http.routers.gl.entrypoints=websecure"
      - "traefik.http.routers.gl.tls=true"
      - "traefik.http.routers.gl.tls.certresolver=letsencrypt"
      - "traefik.http.services.gl.loadbalancer.server.port=80"
      - "traefik.http.routers.gl-http.rule=Host(`gl.oceaniaparkhotel.com.br`)"
      - "traefik.http.routers.gl-http.entrypoints=web"
      - "traefik.http.routers.gl-http.middlewares=gl-redirect"
      - "traefik.http.middlewares.gl-redirect.redirectscheme.scheme=https"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || wget -qO- http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s